/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'alerts': RouteRecordInfo<'alerts', '/alerts', Record<never, never>, Record<never, never>>,
    'alerts-catalogs-alert-statuses': RouteRecordInfo<'alerts-catalogs-alert-statuses', '/alerts/catalogs/alertStatuses', Record<never, never>, Record<never, never>>,
    'alerts-catalogs-event-classifications': RouteRecordInfo<'alerts-catalogs-event-classifications', '/alerts/catalogs/eventClassifications', Record<never, never>, Record<never, never>>,
    'alerts-catalogs-type-events': RouteRecordInfo<'alerts-catalogs-type-events', '/alerts/catalogs/typeEvents', Record<never, never>, Record<never, never>>,
    'callback': RouteRecordInfo<'callback', '/callback', Record<never, never>, Record<never, never>>,
    'coes-job-positions': RouteRecordInfo<'coes-job-positions', '/coes/jobPositions', Record<never, never>, Record<never, never>>,
    'coes-persons': RouteRecordInfo<'coes-persons', '/coes/persons', Record<never, never>, Record<never, never>>,
    'coes-position-persons': RouteRecordInfo<'coes-position-persons', '/coes/positionPersons', Record<never, never>, Record<never, never>>,
    'coes-type-contracts': RouteRecordInfo<'coes-type-contracts', '/coes/typeContracts', Record<never, never>, Record<never, never>>,
    'coes-type-events': RouteRecordInfo<'coes-type-events', '/coes/typeEvents', Record<never, never>, Record<never, never>>,
    'educative-institutions-catalogs-area-type-ies': RouteRecordInfo<'educative-institutions-catalogs-area-type-ies', '/educativeInstitutions/catalogs/areaTypeIes', Record<never, never>, Record<never, never>>,
    'educative-institutions-catalogs-education-levels': RouteRecordInfo<'educative-institutions-catalogs-education-levels', '/educativeInstitutions/catalogs/educationLevels', Record<never, never>, Record<never, never>>,
    'educative-institutions-catalogs-form-attentions': RouteRecordInfo<'educative-institutions-catalogs-form-attentions', '/educativeInstitutions/catalogs/formAttentions', Record<never, never>, Record<never, never>>,
    'educative-institutions-catalogs-institution-characteristics': RouteRecordInfo<'educative-institutions-catalogs-institution-characteristics', '/educativeInstitutions/catalogs/institutionCharacteristics', Record<never, never>, Record<never, never>>,
    'educative-institutions-catalogs-management-sector-ies': RouteRecordInfo<'educative-institutions-catalogs-management-sector-ies', '/educativeInstitutions/catalogs/managementSectorIes', Record<never, never>, Record<never, never>>,
    'educative-institutions-catalogs-management-types': RouteRecordInfo<'educative-institutions-catalogs-management-types', '/educativeInstitutions/catalogs/managementTypes', Record<never, never>, Record<never, never>>,
    'educative-institutions-catalogs-program-type-ies': RouteRecordInfo<'educative-institutions-catalogs-program-type-ies', '/educativeInstitutions/catalogs/programTypeIes', Record<never, never>, Record<never, never>>,
    'educative-institutions-catalogs-shift-type-ies': RouteRecordInfo<'educative-institutions-catalogs-shift-type-ies', '/educativeInstitutions/catalogs/shiftTypeIes', Record<never, never>, Record<never, never>>,
    'educative-institutions-catalogs-type-gender-ies': RouteRecordInfo<'educative-institutions-catalogs-type-gender-ies', '/educativeInstitutions/catalogs/typeGenderIes', Record<never, never>, Record<never, never>>,
    'imports-escale': RouteRecordInfo<'imports-escale', '/imports/escale', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'login copy': RouteRecordInfo<'login copy', '/login copy', Record<never, never>, Record<never, never>>,
    'modules': RouteRecordInfo<'modules', '/modules', Record<never, never>, Record<never, never>>,
    'modules-page-new-module': RouteRecordInfo<'modules-page-new-module', '/modules/pageNewModule', Record<never, never>, Record<never, never>>,
    'not-authorized': RouteRecordInfo<'not-authorized', '/not-authorized', Record<never, never>, Record<never, never>>,
    'register': RouteRecordInfo<'register', '/register', Record<never, never>, Record<never, never>>,
    'register copy': RouteRecordInfo<'register copy', '/register copy', Record<never, never>, Record<never, never>>,
    'second-page': RouteRecordInfo<'second-page', '/second-page', Record<never, never>, Record<never, never>>,
    'test-axios': RouteRecordInfo<'test-axios', '/test-axios', Record<never, never>, Record<never, never>>,
    'test-image-viewer': RouteRecordInfo<'test-image-viewer', '/test-image-viewer', Record<never, never>, Record<never, never>>,
    'third-page': RouteRecordInfo<'third-page', '/third-page', Record<never, never>, Record<never, never>>,
    'users': RouteRecordInfo<'users', '/users', Record<never, never>, Record<never, never>>,
  }
}
